<a href="https://colab.research.google.com/github/weleba77/machine-Leaning-/blob/main/LLM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import torch
import torch.nn as nn
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [2]:
with open ('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
  text = f.read()
print(len(text))




232307


In [4]:
print(text[:200])

DOROTHY AND THE WIZARD IN OZ

  BY

  L. FRANK BAUM

  AUTHOR OF THE WIZARD OF OZ, THE LAND OF OZ, OZMA OF OZ, ETC.

  ILLUSTRATED BY JOHN R. NEILL

  BOOKS OF WONDER WILLIAM MORROW & CO., INC. NEW Y


In [5]:

chars = sorted(set(text))
print(chars)


['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


In [6]:
print(len(chars))

81


In [7]:
string_to_int = {ch: i for i, ch in enumerate(chars) }
int_to_string = {i: ch for i, ch in enumerate(chars) }
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

encode('hello')

[61, 58, 65, 65, 68]

In [8]:
decode([61, 58, 65, 65, 68])

'hello'

In [9]:
import torch

In [10]:
data = torch.tensor(encode(text), dtype= torch.long)
print(data[:100])

tensor([80, 28, 39, 42, 39, 44, 32, 49,  1, 25, 38, 28,  1, 44, 32, 29,  1, 47,
        33, 50, 25, 42, 28,  1, 33, 38,  1, 39, 50,  0,  0,  1,  1, 26, 49,  0,
         0,  1,  1, 36, 11,  1, 30, 42, 25, 38, 35,  1, 26, 25, 45, 37,  0,  0,
         1,  1, 25, 45, 44, 32, 39, 42,  1, 39, 30,  1, 44, 32, 29,  1, 47, 33,
        50, 25, 42, 28,  1, 39, 30,  1, 39, 50,  9,  1, 44, 32, 29,  1, 36, 25,
        38, 28,  1, 39, 30,  1, 39, 50,  9,  1])


In [11]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

In [12]:
block_size = 8
x = train_data[:block_size]
y = train_data[1:block_size + 1]

for t in range(block_size):
  context = x[:t+1]
  target = y[t]
  print('when input is', context, " target is", target)

when input is tensor([80])  target is tensor(28)
when input is tensor([80, 28])  target is tensor(39)
when input is tensor([80, 28, 39])  target is tensor(42)
when input is tensor([80, 28, 39, 42])  target is tensor(39)
when input is tensor([80, 28, 39, 42, 39])  target is tensor(44)
when input is tensor([80, 28, 39, 42, 39, 44])  target is tensor(32)
when input is tensor([80, 28, 39, 42, 39, 44, 32])  target is tensor(49)
when input is tensor([80, 28, 39, 42, 39, 44, 32, 49])  target is tensor(1)


torch example

In [13]:
randint = torch.randint(-100,100,(6,))
randint

tensor([ 81,  54, -71,  76, -90,  88])

In [14]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1],[4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [15]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:

ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
arange= torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [20]:
linspace = torch.linspace(3, 10, steps = 5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [21]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 1],
        [5, 0, 0]])

In [23]:
import numpy as np
import time

In [24]:
start_time = time.time()

zeros= torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00021982


In [25]:
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)
np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

1.02420592
0.22327399


/tmp/ipykernel_2090/3879101734.py:14: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


In [26]:
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [27]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [28]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [31]:
batch_size = 4
block_size = 8

In [32]:
n = int(0.8 * len(data))

train_data1 = data[:n]
val_data1 = data[n:]

def get_batch(split):
    data = train_data1 if split == 'train' else val_data1

    ix = torch.randint(len(data) - block_size, (batch_size,))
    print(ix)

    x = torch.stack([data[i:i + block_size] for i in ix])

    y = torch.stack([data[i + 1:i + block_size + 1] for i in ix])

    return x, y

x, y = get_batch('train')

print('input:')
print(x)

print('targets:')
print(y)


tensor([ 13784,  50777,  20849, 137697])
input:
tensor([[57,  1, 73, 61, 58, 66,  1, 55],
        [68, 11,  3,  0,  0,  3, 26, 74],
        [61, 58,  0, 55, 68, 73, 73, 68],
        [69, 65, 62, 58, 57, 11,  0,  0]])
targets:
tensor([[ 1, 73, 61, 58, 66,  1, 55, 54],
        [11,  3,  0,  0,  3, 26, 74, 73],
        [58,  0, 55, 68, 73, 73, 68, 66],
        [65, 62, 58, 57, 11,  0,  0,  3]])


In [41]:
x = train_data1[:block_size]
y = train_data1[1:block_size + 1]

for t in range(block_size):
    context = x[:t + 1]
    target = y[t]

    print('when input is', context, "target is", target)

when input is tensor([80]) target is tensor(28)
when input is tensor([80, 28]) target is tensor(39)
when input is tensor([80, 28, 39]) target is tensor(42)
when input is tensor([80, 28, 39, 42]) target is tensor(39)
when input is tensor([80, 28, 39, 42, 39]) target is tensor(44)
when input is tensor([80, 28, 39, 42, 39, 44]) target is tensor(32)
when input is tensor([80, 28, 39, 42, 39, 44, 32]) target is tensor(49)
when input is tensor([80, 28, 39, 42, 39, 44, 32, 49]) target is tensor(1)


In [57]:
class BigramLanguageModel(nn.Module):
  def __init__ (self, vocab_size):
    super().__init__()
    self.token_enbeddding_table = nn.Embedding(vocab_size, vocab_size)
  def forward (self, index, target):
    logits = self.token_enbeddding_table(index)
    return logits
